use crate::hash::{combine, to_hex};
use crate::model::{Edges, Entity, SourceKind};
use regex::Regex;
use std::collections::BTreeMap;
use std::io::Write;
use std::path::Path;
use std::sync::LazyLock;

static SECTION: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"(?m)^##\s+(.+)$").unwrap());

pub fn parse_sections(text: &str) -> BTreeMap<String, String> {
    let mut sections = BTreeMap::new();
    let caps: Vec<_> = SECTION.captures_iter(text).collect();
    for (i, cap) in caps.iter().enumerate() {
        let m = cap.get(0).expect("capture group 0 always present");
        let heading = cap[1].trim().to_string();
        let start = m.end();
        let end = if i + 1 < caps.len() {
            caps[i + 1]
                .get(0)
                .expect("capture group 0 always present")
                .start()
        } else {
            text.len()
        };
        sections.insert(heading, text[start..end].trim_matches('\n').to_string());
    }
    sections
}

pub fn read_preserved_notes(path: &Path) -> String {
    match std::fs::read_to_string(path) {
        Ok(text) => parse_sections(&text)
            .get("Notes")
            .cloned()
            .unwrap_or_default()
            .trim()
            .to_string(),
        Err(_) => String::new(),
    }
}

fn link_name(id: &str, entities: &BTreeMap<String, Entity>) -> Option<String> {
    entities.get(id).map(|e| format!("[[{}]]", e.name))
}

pub fn render_page(
    entity: &Entity,
    edges: &Edges,
    entities: &BTreeMap<String, Entity>,
    preserved_notes: &str,
) -> String {
    let mut out = String::new();
    out.push_str(&format!("# {}\n\n", entity.name));
    out.push_str("<!-- generated by wiki compiler — do not edit compiler-owned sections -->\n\n");

    // Metadata (always present)
    out.push_str("## Metadata\n");
    out.push_str(&format!(
        "- created: {}\n",
        if entity.created.is_empty() {
            "unknown"
        } else {
            &entity.created
        }
    ));
    if !entity.aliases.is_empty() {
        out.push_str(&format!("- aliases: {}\n", entity.aliases.join(", ")));
    }
    out.push_str(&format!("- kind: {}\n", entity.kind.label()));
    out.push_str(&format!("- source: {}\n", entity.source_path));
    out.push_str(&format!(
        "- source_hash: {}\n\n",
        to_hex(&entity.content_hash)
    ));

    // Related (omit if empty)
    let related: Vec<String> = edges
        .outgoing
        .iter()
        .filter_map(|id| link_name(id, entities))
        .collect();
    if !related.is_empty() {
        out.push_str("## Related\n");
        for l in &related {
            out.push_str(&format!("- {l}\n"));
        }
        out.push('\n');
    }

    // Referenced By (omit if empty)
    let refby: Vec<String> = edges
        .incoming
        .iter()
        .filter_map(|id| link_name(id, entities))
        .collect();
    if !refby.is_empty() {
        out.push_str("## Referenced By\n");
        for l in &refby {
            out.push_str(&format!("- {l}\n"));
        }
        out.push('\n');
    }

    // Code-only sections
    if let SourceKind::Code { .. } = entity.kind {
        if !entity.symbols.is_empty() {
            out.push_str("## Exports\n");
            for s in &entity.symbols {
                out.push_str(&format!("- `{s}`\n"));
            }
            out.push('\n');
        }
        if !entity.imports.is_empty() {
            out.push_str("## Imports\n");
            for i in &entity.imports {
                out.push_str(&format!("- {i}\n"));
            }
            out.push('\n');
        }
    }

    // Body (omit if empty)
    if !entity.body.trim().is_empty() {
        out.push_str("## Body\n");
        out.push_str(entity.body.trim());
        out.push_str("\n\n");
    }

    // Notes (human-owned, always present so there is a home for hand edits)
    out.push_str("## Notes\n");
    if preserved_notes.trim().is_empty() {
        out.push_str("_(add your own notes here — preserved on recompile)_\n");
    } else {
        out.push_str(preserved_notes.trim());
        out.push('\n');
    }

    out
}

pub fn render_fingerprint(
    entity: &Entity,
    edges: &Edges,
    entities: &BTreeMap<String, Entity>,
    preserved_notes: &str,
) -> [u8; 32] {
    let out_names: Vec<String> = edges
        .outgoing
        .iter()
        .filter_map(|id| entities.get(id).map(|e| e.name.clone()))
        .collect();
    let in_names: Vec<String> = edges
        .incoming
        .iter()
        .filter_map(|id| entities.get(id).map(|e| e.name.clone()))
        .collect();
    combine(&[
        entity.name.as_bytes(),
        entity.created.as_bytes(),
        entity.kind.label().as_bytes(),
        entity.source_path.as_bytes(),
        entity.body.as_bytes(),
        entity.aliases.join(",").as_bytes(),
        entity.symbols.join(",").as_bytes(),
        entity.imports.join(",").as_bytes(),
        out_names.join(",").as_bytes(),
        in_names.join(",").as_bytes(),
        preserved_notes.trim().as_bytes(),
        entity.summary.as_deref().unwrap_or("").as_bytes(),
    ])
}

/// Write via a temp file + rename so an interrupted run can't leave a half-written page.
pub fn write_atomic(path: &Path, content: &str) -> std::io::Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let mut tmp = path.as_os_str().to_owned();
    tmp.push(".tmp");
    let tmp = std::path::PathBuf::from(tmp);
    {
        let f = std::fs::File::create(&tmp)?;
        let mut w = std::io::BufWriter::new(f);
        w.write_all(content.as_bytes())?;
        w.flush()?;
    }
    std::fs::rename(&tmp, path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::graph::build_graph;
    use crate::model::{Entity, SourceKind};
    use std::collections::BTreeMap;

    fn ent(id: &str, name: &str, body: &str) -> Entity {
        Entity {
            id: id.into(),
            name: name.into(),
            aliases: vec![],
            created: "2026-01-01".into(),
            body: body.into(),
            source_path: format!("{id}.txt"),
            kind: SourceKind::Text,
            content_hash: [0u8; 32],
            summary: None,
            symbols: vec![],
            imports: vec![],
        }
    }
    fn map(v: Vec<Entity>) -> BTreeMap<String, Entity> {
        v.into_iter().map(|e| (e.id.clone(), e)).collect()
    }

    #[test]
    fn related_and_referenced_by_rendered() {
        let ents = map(vec![
            ent("alpha", "Alpha", "mentions Beta"),
            ent("beta", "Beta", "nothing"),
        ]);
        let g = build_graph(&ents);
        let a = render_page(&ents["alpha"], &g.edges["alpha"], &ents, "");
        let b = render_page(&ents["beta"], &g.edges["beta"], &ents, "");
        assert!(a.contains("## Related") && a.contains("[[Beta]]"));
        assert!(b.contains("## Referenced By") && b.contains("[[Alpha]]"));
        assert!(a.contains("generated"));
    }

    #[test]
    fn preserved_notes_survive() {
        let ents = map(vec![ent("alpha", "Alpha", "body")]);
        let g = build_graph(&ents);
        let page = render_page(&ents["alpha"], &g.edges["alpha"], &ents, "MY HAND NOTES");
        assert!(page.contains("MY HAND NOTES"));
        let sections = parse_sections(&page);
        assert_eq!(
            sections.get("Notes").map(|s| s.trim()),
            Some("MY HAND NOTES")
        );
    }

    #[test]
    fn fingerprint_changes_with_incoming_edges() {
        let ents1 = map(vec![
            ent("a", "Alpha", "nothing"),
            ent("b", "Beta", "nothing"),
        ]);
        let g1 = build_graph(&ents1);
        let f1 = render_fingerprint(&ents1["a"], &g1.edges["a"], &ents1, "");
        let ents2 = map(vec![
            ent("a", "Alpha", "nothing"),
            ent("b", "Beta", "mentions Alpha"),
        ]);
        let g2 = build_graph(&ents2);
        let f2 = render_fingerprint(&ents2["a"], &g2.edges["a"], &ents2, "");
        assert_ne!(f1, f2); // Alpha gained an incoming edge → must re-render
    }
}
