#!/usr/bin/env bash
# Unit test for strip-chrome.awk — no network, deterministic.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AWK="$SCRIPT_DIR/strip-chrome.awk"
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
fail=0
ok()  { echo "  ok: $1"; }
bad() { echo "  FAIL: $1"; fail=1; }
# Assert helpers (each branch is terminal — no operator-precedence footgun):
present()   { printf '%s\n' "$1" | grep -q  -- "$2" && ok "present: $2" || bad "MISSING: $2"; }
absent()    { printf '%s\n' "$1" | grep -q  -- "$2" && bad "LEAKED: $2"  || ok "absent: $2"; }
present_f() { printf '%s\n' "$1" | grep -Fq -- "$2" && ok "present: $2" || bad "MISSING: $2"; }
absent_f()  { printf '%s\n' "$1" | grep -Fq -- "$2" && bad "LEAKED: $2"  || ok "absent: $2"; }

# Fixture 1 — standard rendered page.
cat > "$tmp/page.md" <<'EOF'
# Alpha

<!-- generated by wiki compiler — do not edit compiler-owned sections -->

## Metadata
- kind: text

## Related
- [[beta|Beta]]

## Referenced By
- [[gamma|Gamma]]

## Body
Alpha body text.

## Notes
_(add your own notes here — preserved on recompile)_
EOF
out="$(awk -f "$AWK" "$tmp/page.md")"
absent    "$out" "## Referenced By"
absent_f  "$out" "[[gamma|Gamma]]"
absent    "$out" "## Notes"
absent    "$out" "add your own notes"
present   "$out" "## Metadata"
present   "$out" "## Related"
present_f "$out" "[[beta|Beta]]"
present   "$out" "## Body"
present   "$out" "Alpha body text"

# Fixture 2 — robustness: a markdown-source body that itself contains literal
# "## Referenced By" and "## Notes" headings. Only the compiler sections
# (the FIRST RefBy, the LAST Notes) must be removed.
cat > "$tmp/doc.md" <<'EOF'
# Doc

## Metadata
- kind: markdown

## Referenced By
- [[x|X]]

## Body
Intro paragraph.

## Referenced By
Real source heading — keep this.

## Notes
Author's real notes in the source — keep these.

More body after the source notes.

## Notes
_(add your own notes here — preserved on recompile)_
EOF
out2="$(awk -f "$AWK" "$tmp/doc.md")"
absent_f  "$out2" "[[x|X]]"
present   "$out2" "Real source heading"
present   "$out2" "Author's real notes"
present   "$out2" "More body after"
absent    "$out2" "add your own notes"

# Fixture 3 — idempotence.
once="$(awk -f "$AWK" "$tmp/page.md")"
twice="$(printf '%s\n' "$once" | awk -f "$AWK")"
[ "$once" = "$twice" ] && ok "idempotent" || bad "not idempotent"

if [ "$fail" -eq 0 ]; then echo "strip-chrome: ALL PASS"; else echo "strip-chrome: FAILURES"; exit 1; fi
